services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27015:27017"
    volumes:
      - mongo_data:/data/db

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-items_db}
      GO_POSTGRES_DB: ${GO_POSTGRES_DB:-products}
    restart: unless-stopped
    ports:
      - "5435:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  api-node:
    build: ./services/api-node
    image: api-node:dev     
    env_file:
      - .env.example
    environment:
      MONGO_URI: ${MONGO_URI}
      PORT: ${NODE_PORT:-4000}
    depends_on:
      - mongo
    ports:
      - "4005:4000"

  api-python:
    build: ./services/api-python
    image: api-python:dev   
    env_file:
      - .env.example
    environment:
      DATABASE_URL: ${POSTGRES_URI}
      PORT: ${PY_PORT:-5000}
    depends_on:
      - postgres
    ports:
      - "5005:5000"

  api-go:
    build: ./services/api-go
    image: api-go:dev   
    env_file:
      - .env.example
    environment:
      DATABASE_URL: ${GO_DATABASE_URL}
      PORT: ${GO_PORT:-7000}
    depends_on:
      - postgres
    ports:
      - "7005:7000"

  web-frontend:
    build:
      context: ./services/web-frontend
      args:
      - VITE_NODE_API_URL=http://api-node.ms-starter.svc.cluster.local
      - VITE_PY_API_URL=http://api-python.ms-starter.svc.cluster.local
      - VITE_GO_API_URL=http://api-go.ms-starter.svc.cluster.local
    image: web-frontend:dev
    env_file:
      - .env.example
    depends_on:
      - api-node
      - api-python
      - api-go
    ports:
      - "5173:80"

volumes:
  mongo_data:
  pg_data: