apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: ms-starter
type: Opaque
stringData:
  MONGO_USER: mongo
  MONGO_PASSWORD: mongo
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  GO_POSTGRES_USER: postgres
  GO_POSTGRES_PASSWORD: postgres