apiVersion: v1
kind: Service
metadata:
  name: api-node
  namespace: ms-starter
spec:
  selector: { app: api-node }
  ports:
    - port: 80
      targetPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-node
  namespace: ms-starter
spec:
  replicas: 1
  selector:
    matchLabels: { app: api-node }
  template:
    metadata:
      labels: { app: api-node }
    spec:
      containers:
        - name: api-node
          image: api-node:dev
          imagePullPolicy: IfNotPresent
          ports: [{ containerPort: 4000 }]
          env:
            - name: PORT
              value: "4000"
            - name: MONGO_DB
              valueFrom: { configMapKeyRef: { name: app-config, key: MONGO_DB } }
            # bring the same secret into the API pod
            - name: MONGO_USER
              valueFrom: { secretKeyRef: { name: app-secrets, key: MONGO_USER } }
            - name: MONGO_PASSWORD
              valueFrom: { secretKeyRef: { name: app-secrets, key: MONGO_PASSWORD } }
            - name: MONGO_URI
              value: "mongodb://$(MONGO_USER):$(MONGO_PASSWORD)@mongo.ms-starter.svc.cluster.local:27017/?authSource=admin&directConnection=true"