apiVersion: v1
kind: Service
metadata:
  name: api-node
  namespace: ms-starter
spec:
  selector: { app: api-node }
  ports:
    - port: 80
      targetPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-node
  namespace: ms-starter
spec:
  replicas: 1
  selector:
    matchLabels: { app: api-node }
  template:
    metadata:
      labels: { app: api-node }
    spec:
      containers:
        - name: api-node
          image: ghcr.io/example/api-node:latest
          ports: [{ containerPort: 4000 }]
          env:
            - name: PORT
              value: "4000"
            - name: MONGO_DB
              valueFrom: { configMapKeyRef: { name: app-config, key: MONGO_DB } }
            - name: MONGO_URI
              value: "mongodb://mongo.ms-starter.svc.cluster.local:27017"