apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ms-starter-ingress
  namespace: ms-starter
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: app.local
      http:
        paths:
          # Frontend: keep path after "/" (root) -> "/$1"
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: web-frontend
                port:
                  number: 80

          # Node API: strip "/api-node" prefix
          - path: /api-node/?(.*)
            pathType: Prefix
            backend:
              service:
                name: api-node
                port:
                  number: 80

          # Python API: strip "/api-python" prefix
          - path: /api-python/?(.*)
            pathType: Prefix
            backend:
              service:
                name: api-python
                port:
                  number: 80